### ISSUE TITLE
"Cannot continue a constrained optimization" when using "dihedral_correction" method from "ForceFieldGenerator()"

### ISSUE THREAD

**Issue by pfloris** [kthpanor/echem#14]
I get the error "Cannot continue a constrained optimization; please implement constrained optimization in Cartesian coordinates" when using the function `dihedral_correction()` from the `ForceFieldGenerator()` module. **What could this mean in practice?**

I should add that the xyz scan file that I use contains only 2 structures, for a matter of limited resources and time available to me. **Could this be the reason (or on of the reasons) for the error?**

Should you need some working example, I will provide you with one.

Thanks,
Paolo

**Comment by iubr** [comment]
Hi Paolo,

I will look into this over the weekend. Could you send me your example? Thanks and sorry for the slow answer..

/Iulia

**Comment by pfloris** [comment]
This compressed folder should contain everything to reproduce the error. I have added a line in the GAFF extension file because I get an error otherwise (dihedral type 'ca-ca-ca-os' is not present in GAFF).

[example.zip](https://github.com/kthpanor/echem/files/13674346/example.zip)

PS. Not slow at all! And no problem :)

**Comment by iubr** [comment]
It seems that the error is very particular to the molecule, molecular configuration, and value to which an internal coordinate is constrained during the constrained geometry optimization. It arises at some point during the optimization using a force field gradient, when geomeTRIC is no longer able to build the internal coordinate system (probably due to the very strange bond lengths and angles of the last optimization step). GeomeTRIC then tries to switch to constrained optimization using Cartesian coordinates, which is not yet implemented and results in the error. Several optimization steps actually work normally until the particular conformation is reached. Starting from a different initial conformation and constraining the internal coordinate differently fixes the issue. Since the error is rather related to the starting point, than the code itself, I close this issue.
